import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar";
import ReactQueryProvider from "@/providers/ReactQueryProvider";
import { Toaster } from "sonner";
import AuthProvider from "./Components/AuthProvider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Inquistive Mind Academy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
      
       

<ReactQueryProvider>
<AuthProvider>
  <Navbar></Navbar>
        {children}
       
        </AuthProvider>
        </ReactQueryProvider>
        <Toaster
  position="bottom-right"
  richColors
  closeButton
  expand
  duration={3000}
  toastOptions={{
    className:
      "!rounded-2xl !border !border-orange-100 !bg-white !text-slate-800 !shadow-2xl",
    style: {
      fontSize: "14px",
      fontWeight: 500,
      padding: "16px",
    },
  }}
/>
        </body>
    </html>
  );
}
