import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar";
import ReactQueryProvider from "@/providers/ReactQueryProvider";
import { Toaster } from "sonner";
import AuthProvider from "./Components/AuthProvider";
import { Inter, Poppins } from "next/font/google";




export const metadata = {
  title: "Inquistive Mind Academy",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-body",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-heading",
});

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${poppins.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
      
       

<ReactQueryProvider>
<AuthProvider>
  <Navbar></Navbar>
        {children}
       
        </AuthProvider>
        </ReactQueryProvider>
        <Toaster
  position="bottom-right"
  richColors
  closeButton
  expand
  duration={3000}
  toastOptions={{
    className:
      "!rounded-2xl !border !border-orange-100 !bg-white !text-slate-800 !shadow-2xl",
    style: {
      fontSize: "14px",
      fontWeight: 500,
      padding: "16px",
    },
  }}
/>
        </body>
    </html>
  );
}
